/* -*- mode: c; c-basic-offset: 2; indent-tabs-mode: nil; -*-
 * DO NOT EDIT; autogenerated by http://github.com/hzeller/bdfont.data
 * Font-File: smalltext.bdf
 *      Font: -Misc-Fixed-Medium-R-Normal--18-120-100-100-C-90-ISO10646-1
 *      Size: 18   Baseline at: 11
 * For chars: 0123456789.l/minStartingx_-coolonoff ()Leak!≈
 */

#include "font-smalltext.h"

static const uint8_t PROGMEM _font_data_smalltext[] = {
  /* codepoint ' ' plain bytes */

  /* codepoint '!' plain bytes */
  0x7f,
  0x06,

  /* codepoint '(' plain bytes */
  0xf8,0x06,0x01,
  0x01,0x06,0x08,

  /* codepoint ')' plain bytes */
  0x01,0x06,0xf8,
  0x08,0x06,0x01,

  /* codepoint '-' RLE/nibble */
  0x07,0x40,

  /* codepoint '.' plain bytes */
  0x06,0x06,

  /* codepoint '/' RLE/4 */
  0x56,0x00,0x80,0x60,0x10,  0x05,0x0c,0x02,
  0xb5,0x04,0x03,0x00,0x00,

  /* codepoint '0' plain bytes */
  0xf8,0x04,0x02,0x02,0x02,0x04,0xf8,
  0x01,0x02,0x04,0x04,0x04,0x02,0x01,

  /* codepoint '1' RLE/4 */
  0x55,0x10,0x08,0x04,0xfe,  0x03,0x00,
  0x37,0x04,0x07,0x04,

  /* codepoint '2' plain bytes */
  0x08,0x04,0x02,0x82,0x42,0x24,0x18,
  0x04,0x06,0x05,0x04,0x04,0x04,0x04,

  /* codepoint '3' plain bytes */
  0x02,0x02,0x02,0x22,0x32,0x4a,0x86,
  0x02,0x04,0x04,0x04,0x04,0x02,0x01,

  /* codepoint '4' plain bytes */
  0xc0,0xa0,0x90,0x88,0x84,0xfe,0x80,
  0x00,0x00,0x00,0x00,0x00,0x07,0x00,

  /* codepoint '5' RLE/nibble */
  0x41,0x3e,0x22,  0x11,0x42,0x82,
  0x41,0x02,0x04,  0x11,0x02,0x01,

  /* codepoint '6' plain bytes */
  0xf8,0x44,0x22,0x22,0x22,0x42,0x80,
  0x01,0x02,0x04,0x04,0x04,0x02,0x01,

  /* codepoint '7' RLE/4 */
  0x57,0x02,0x82,0x62,0x1a,  0x01,0x06,
  0x37,0x00,0x07,0x00,

  /* codepoint '8' plain bytes */
  0x88,0x54,0x22,0x22,0x22,0x54,0x88,
  0x01,0x02,0x04,0x04,0x04,0x02,0x01,

  /* codepoint '9' plain bytes */
  0x18,0x24,0x42,0x42,0x42,0x24,0xf8,
  0x00,0x04,0x04,0x04,0x04,0x02,0x01,

  /* codepoint 'L' RLE/nibble */
  0x61,0xfe,0x00,
  0x61,0x07,0x04,

  /* codepoint 'S' RLE/nibble */
  0x51,0x1c,0x22,  0x01,0xc4,
  0x51,0x02,0x04,  0x01,0x03,

  /* codepoint '_' RLE/nibble */
  0x08,0x08,

  /* codepoint 'a' RLE/nibble */
  0x51,0x00,0x90,  0x01,0xe0,
  0x41,0x03,0x04,  0x11,0x02,0x07,

  /* codepoint 'c' RLE/nibble */
  0x51,0xe0,0x10,  0x01,0x20,
  0x51,0x03,0x04,  0x01,0x02,

  /* codepoint 'e' RLE/nibble */
  0x51,0xe0,0x90,  0x01,0xe0,
  0x51,0x03,0x04,  0x01,0x02,

  /* codepoint 'f' RLE/4 */
  0x66,0x40,0xfc,0x42,0x02,  0x01,0x0c,
  0x76,0x00,0x07,0x00,0x00,

  /* codepoint 'g' RLE/nibble */
  0x41,0xe0,0x10,  0x11,0xe0,0x10,
  0x41,0x1a,0x25,  0x11,0x24,0x18,

  /* codepoint 'i' RLE/4 */
  0x95,0x10,0x12,0xf2,0x00,
  0x26,0x04,0x07,0x04,

  /* codepoint 'k' plain bytes */
  0xfe,0x00,0x80,0xc0,0x20,0x10,0x00,
  0x07,0x01,0x00,0x00,0x01,0x02,0x04,

  /* codepoint 'l' RLE/4 */
  0x26,0x02,0xfe,0x00,
  0x26,0x04,0x07,0x04,

  /* codepoint 'm' plain bytes */
  0xf0,0x10,0x10,0xe0,0x10,0x10,0xe0,
  0x07,0x00,0x00,0x03,0x00,0x00,0x07,

  /* codepoint 'n' RLE/nibble */
  0x11,0xf0,0x20,  0x14,0x10,0xe0,
  0x51,0x07,0x00,  0x01,0x07,

  /* codepoint 'o' RLE/nibble */
  0x51,0xe0,0x10,  0x01,0xe0,
  0x51,0x03,0x04,  0x01,0x03,

  /* codepoint 'r' RLE/4 */
  0xd5,0x10,0xe0,0x20,0x10,  0x01,0x60,
  0xb5,0x00,0x07,0x00,0x00,

  /* codepoint 't' RLE/4 */
  0x76,0x10,0xfc,0x10,0x00,
  0x76,0x00,0x03,0x04,0x02,

  /* codepoint 'x' plain bytes */
  0x10,0x20,0x40,0x80,0x40,0x20,0x10,
  0x04,0x02,0x01,0x00,0x01,0x02,0x04,

  /* codepoint U+2248 plain bytes */
  0x20,0x90,0x90,0x20,0x40,0x40,0x20,
  0x01,0x00,0x00,0x01,0x02,0x02,0x01,
};

static const struct GlyphData PROGMEM _font_glyphs_smalltext[] = {
  {.codepoint = ' ',    .width= 9, .stripe_begin=1, .stripe_end=0, .left_margin=0, .right_margin=0, BDFONT_PLAIN(0), .data_offset=   0},
  {.codepoint = '!',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=4, .right_margin=4, BDFONT_PLAIN(0), .data_offset=   0},
  {.codepoint = '(',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=3, .right_margin=3, BDFONT_PLAIN(0), .data_offset=   2},
  {.codepoint = ')',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=3, .right_margin=3, BDFONT_PLAIN(0), .data_offset=   8},
  {.codepoint = '-',    .width= 9, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset=  14},
  {.codepoint = '.',    .width= 9, .stripe_begin=1, .stripe_end=2, .left_margin=4, .right_margin=3, BDFONT_PLAIN(0), .data_offset=  16},
  {.codepoint = '/',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset=  18},
  {.codepoint = '0',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  31},
  {.codepoint = '1',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset=  45},
  {.codepoint = '2',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  56},
  {.codepoint = '3',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  70},
  {.codepoint = '4',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  84},
  {.codepoint = '5',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset=  98},
  {.codepoint = '6',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 110},
  {.codepoint = '7',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 124},
  {.codepoint = '8',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 135},
  {.codepoint = '9',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 149},
  {.codepoint = 'L',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 163},
  {.codepoint = 'S',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 169},
  {.codepoint = '_',    .width= 9, .stripe_begin=1, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 179},
  {.codepoint = 'a',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 181},
  {.codepoint = 'c',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 192},
  {.codepoint = 'e',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 202},
  {.codepoint = 'f',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 212},
  {.codepoint = 'g',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 224},
  {.codepoint = 'i',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=2, BDFONT_RLE(2)  , .data_offset= 236},
  {.codepoint = 'k',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 245},
  {.codepoint = 'l',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=2, BDFONT_RLE(2)  , .data_offset= 259},
  {.codepoint = 'm',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 267},
  {.codepoint = 'n',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 281},
  {.codepoint = 'o',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 292},
  {.codepoint = 'r',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 302},
  {.codepoint = 't',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 314},
  {.codepoint = 'x',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 324},
  {.codepoint = 0x2248, .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 338},
};

const struct FontData PROGMEM font_smalltext = {
  .available_glyphs = 35,
  .baseline = 11,
  .stripes = 2,
  .bits = _font_data_smalltext,
  .glyphs = _font_glyphs_smalltext
};
